services:
  - type: web
    name: electro-store
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn myproject.wsgi:application --chdir myproject
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: electro-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.8

databases:
  - name: electro-db
    databaseName: electro
    user: electro_user
    plan: free
