[pytest]
DJANGO_SETTINGS_MODULE = myproject.settings
pythonpath = .
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --nomigrations --cov=myapp --cov-report=html:htmlcov
norecursedirs = .* build dist venv Lib Scripts include site-packages node_modules