# Generated by Django 6.0.3 on 2026-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_product_reorder_threshold_product_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views_count',
        ),
    ]
