# Generated by Django 6.0.3 on 2026-03-14 19:03

from django.db import migrations


def split_names(apps, schema_editor):
    Brand = apps.get_model('myapp', 'Brand')
    Product = apps.get_model('myapp', 'Product')
    
    for product in Product.objects.all():
        if product.name and not product.model_name:
            parts = product.name.strip().split()
            if not parts:
                continue
            
            if len(parts) >= 2:
                # Example: "Apple iPhone 15 128GB Blue"
                # brand_name = "Apple"
                # model_name = "iPhone" (User might prefer "iPhone 15" but simple split is word-based)
                # Actually, many brands have two-word models. 
                # Let's try to be a bit smarter or stick to the simple request.
                # "iPhone 15" should ideally be the model.
                
                brand_name = parts[0]
                brand, _ = Brand.objects.get_or_create(name=brand_name)
                product.brand = brand
                
                if len(parts) == 2:
                    product.model_name = parts[1]
                else:
                    # If 3 or more parts, we assume word 2 is model and rest is variant
                    product.model_name = parts[1]
                    product.variant_specs = " ".join(parts[2:])
            else:
                # Only one word — put it in model name
                product.model_name = parts[0]
            
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_brand_product_model_name_product_variant_specs_and_more'),
    ]

    operations = [
        migrations.RunPython(split_names),
    ]
