# Generated by Django 6.0.3 on 2026-03-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RatingIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_ips', to='myapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'ip_address'], name='myapp_ratin_product_d86fde_idx')],
                'unique_together': {('product', 'ip_address')},
            },
        ),
    ]
