# Generated by Django 6.0.2 on 2026-03-17 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_product_rating_sum_product_total_votes_ratingip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ratingip',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='ratingip',
            name='myapp_ratin_product_d86fde_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_sum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='myapp.product'),
        ),
        migrations.RemoveField(
            model_name='ratingip',
            name='product',
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'ip_address'], name='myapp_produ_product_c5d11b_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'customer'], name='myapp_produ_product_9defcf_idx'),
        ),
        migrations.DeleteModel(
            name='RatingIP',
        ),
    ]
