# Generated by Django 6.0.3 on 2026-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_order_discount_amount_coupon_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
