# Generated by Django 6.0.3 on 2026-04-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_migrate_variant_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_images', to='myapp.attributevalue'),
        ),
    ]
