# Generated by Django 6.0.3 on 2026-04-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_productimage_attribute_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('customer', 'product'), name='unique_customer_product_no_variant'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('customer', 'product', 'variant'), name='unique_customer_product_variant'),
        ),
    ]
