# Generated by Django 6.0.3 on 2026-04-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_product_image_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
    ]
