# Generated by Django 6.0.3 on 2026-04-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_productimage_variant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_customer_product_no_variant',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_customer_product_variant',
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='myapp.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myapp.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='myapp.productvariant'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer', 'variant'], name='myapp_cart_custome_53f43e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('customer', 'variant'), name='unique_customer_variant_cart'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('customer', 'variant'), name='unique_customer_variant_wishlist'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
    ]
